jobs:
  workflow:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Download Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./check/verify

name: Action

on:
  schedule:
    - cron: "25 */6 * * *"
